use crate::definitions::traits::{FromJson,FromJsonError};
use serde_json::Value;

#[derive(Clone, Debug)]
pub enum UNDistinguishingSign {
A,
AFG,
AL,
AM,
AND,
AUS,
AZ,
B,
BD,
BDS,
BF,
BG,
BH,
BIH,
BOL,
BR,
BRN,
BRU,
BS,
BUR,
BVI,
BW,
BY,
CAM,
CDN,
CH,
CI,
CL,
CO,
CR,
CU,
CY,
CZ,
D,
DK,
DOM,
DY,
DZ,
E,
EAK,
EAT,
EAU,
EAZ,
EC,
ER,
ES,
EST,
ET,
ETH,
F,
FIN,
FJI,
FL,
FO,
G,
GB,
GBA,
GBG,
GBJ,
GBM,
GBZ,
GCA,
GE,
GH,
GR,
GUY,
H,
HKJ,
HR,
I,
IL,
IND,
IR,
IRL,
IRQ,
IS,
J,
JA,
K,
KG,
KWT,
KZ,
L,
LAO,
LAR,
LB,
LS,
LT,
LV,
M,
MA,
MAL,
MC,
MD,
MEX,
MGL,
MK,
MNE,
MOC,
MS,
MW,
N,
NA,
NAM,
NAU,
NEP,
NIC,
NL,
NZ,
P,
PA,
PE,
PK,
PL,
PNG,
PY,
Q,
RA,
RC,
RCA,
RCB,
RCH,
RG,
RH,
RI,
RIM,
RL,
RM,
RMM,
RN,
RNR,
RO,
ROK,
ROU,
RP,
RSM,
RU,
RUS,
RWA,
S,
SA,
SD,
SGP,
SK,
SLO,
SME,
SN,
SO,
SRB,
SUD,
SY,
SYR,
T,
TCH,
TD,
TG,
TJ,
TM,
TN,
TR,
TT,
TZA,
UA,
UAE,
USA,
UZ,
V,
VN,
WAG,
WAL,
WAN,
WD,
WG,
WL,
WS,
WV,
YAR,
YV,
ZA,
ZRE,
ZW,
NoneApplicable(String)
}

impl From<String> for UNDistinguishingSign {
    fn from(s: String) -> Self {
        match s.as_str() {
            "A" => Self::A,
            "AFG" => Self::AFG,
            "AL" => Self::AL,
            "AM" => Self::AM,
            "AND" => Self::AND,
            "AUS" => Self::AUS,
            "AZ" => Self::AZ,
            "B" => Self::B,
            "BD" => Self::BD,
            "BDS" => Self::BDS,
            "BF" => Self::BF,
            "BG" => Self::BG,
            "BH" => Self::BH,
            "BIH" => Self::BIH,
            "BOL" => Self::BOL,
            "BR" => Self::BR,
            "BRN" => Self::BRN,
            "BRU" => Self::BRU,
            "BS" => Self::BS,
            "BUR" => Self::BUR,
            "BVI" => Self::BVI,
            "BW" => Self::BW,
            "BY" => Self::BY,
            "CAM" => Self::CAM,
            "CDN" => Self::CDN,
            "CH" => Self::CH,
            "CI" => Self::CI,
            "CL" => Self::CL,
            "CO" => Self::CO,
            "CR" => Self::CR,
            "CU" => Self::CU,
            "CY" => Self::CY,
            "CZ" => Self::CZ,
            "D" => Self::D,
            "DK" => Self::DK,
            "DOM" => Self::DOM,
            "DY" => Self::DY,
            "DZ" => Self::DZ,
            "E" => Self::E,
            "EAK" => Self::EAK,
            "EAT" => Self::EAT,
            "EAU" => Self::EAU,
            "EAZ" => Self::EAZ,
            "EC" => Self::EC,
            "ER" => Self::ER,
            "ES" => Self::ES,
            "EST" => Self::EST,
            "ET" => Self::ET,
            "ETH" => Self::ETH,
            "F" => Self::F,
            "FIN" => Self::FIN,
            "FJI" => Self::FJI,
            "FL" => Self::FL,
            "FO" => Self::FO,
            "G" => Self::G,
            "GB" => Self::GB,
            "GBA" => Self::GBA,
            "GBG" => Self::GBG,
            "GBJ" => Self::GBJ,
            "GBM" => Self::GBM,
            "GBZ" => Self::GBZ,
            "GCA" => Self::GCA,
            "GE" => Self::GE,
            "GH" => Self::GH,
            "GR" => Self::GR,
            "GUY" => Self::GUY,
            "H" => Self::H,
            "HKJ" => Self::HKJ,
            "HR" => Self::HR,
            "I" => Self::I,
            "IL" => Self::IL,
            "IND" => Self::IND,
            "IR" => Self::IR,
            "IRL" => Self::IRL,
            "IRQ" => Self::IRQ,
            "IS" => Self::IS,
            "J" => Self::J,
            "JA" => Self::JA,
            "K" => Self::K,
            "KG" => Self::KG,
            "KWT" => Self::KWT,
            "KZ" => Self::KZ,
            "L" => Self::L,
            "LAO" => Self::LAO,
            "LAR" => Self::LAR,
            "LB" => Self::LB,
            "LS" => Self::LS,
            "LT" => Self::LT,
            "LV" => Self::LV,
            "M" => Self::M,
            "MA" => Self::MA,
            "MAL" => Self::MAL,
            "MC" => Self::MC,
            "MD" => Self::MD,
            "MEX" => Self::MEX,
            "MGL" => Self::MGL,
            "MK" => Self::MK,
            "MNE" => Self::MNE,
            "MOC" => Self::MOC,
            "MS" => Self::MS,
            "MW" => Self::MW,
            "N" => Self::N,
            "NA" => Self::NA,
            "NAM" => Self::NAM,
            "NAU" => Self::NAU,
            "NEP" => Self::NEP,
            "NIC" => Self::NIC,
            "NL" => Self::NL,
            "NZ" => Self::NZ,
            "P" => Self::P,
            "PA" => Self::PA,
            "PE" => Self::PE,
            "PK" => Self::PK,
            "PL" => Self::PL,
            "PNG" => Self::PNG,
            "PY" => Self::PY,
            "Q" => Self::Q,
            "RA" => Self::RA,
            "RC" => Self::RC,
            "RCA" => Self::RCA,
            "RCB" => Self::RCB,
            "RCH" => Self::RCH,
            "RG" => Self::RG,
            "RH" => Self::RH,
            "RI" => Self::RI,
            "RIM" => Self::RIM,
            "RL" => Self::RL,
            "RM" => Self::RM,
            "RMM" => Self::RMM,
            "RN" => Self::RN,
            "RNR" => Self::RNR,
            "RO" => Self::RO,
            "ROK" => Self::ROK,
            "ROU" => Self::ROU,
            "RP" => Self::RP,
            "RSM" => Self::RSM,
            "RU" => Self::RU,
            "RUS" => Self::RUS,
            "RWA" => Self::RWA,
            "S" => Self::S,
            "SA" => Self::SA,
            "SD" => Self::SD,
            "SGP" => Self::SGP,
            "SK" => Self::SK,
            "SLO" => Self::SLO,
            "SME" => Self::SME,
            "SN" => Self::SN,
            "SO" => Self::SO,
            "SRB" => Self::SRB,
            "SUD" => Self::SUD,
            "SY" => Self::SY,
            "SYR" => Self::SYR,
            "T" => Self::T,
            "TCH" => Self::TCH,
            "TD" => Self::TD,
            "TG" => Self::TG,
            "TJ" => Self::TJ,
            "TM" => Self::TM,
            "TN" => Self::TN,
            "TR" => Self::TR,
            "TT" => Self::TT,
            "TZA" => Self::TZA,
            "UA" => Self::UA,
            "UAE" => Self::UAE,
            "USA" => Self::USA,
            "UZ" => Self::UZ,
            "V" => Self::V,
            "VN" => Self::VN,
            "WAG" => Self::WAG,
            "WAL" => Self::WAL,
            "WAN" => Self::WAN,
            "WD" => Self::WD,
            "WG" => Self::WG,
            "WL" => Self::WL,
            "WS" => Self::WS,
            "WV" => Self::WV,
            "YAR" => Self::YAR,
            "YV" => Self::YV,
            "ZA" => Self::ZA,
            "ZRE" => Self::ZRE,
            "ZW" => Self::ZW,
            _ => Self::NoneApplicable(s)
        }
    }
}

impl FromJson for UNDistinguishingSign {
    fn from_json(v: &Value) -> Result<Self, FromJsonError> {
        String::from_json(v).map(Into::into)
    }
}

